### ISSUE TITLE
 Monstruo *existe_monstruo (unCalabozo); 

### ISSUE THREAD

**Issue by yieeei** [IC-ULS/edd-taller2-g1#16]
Podríamos implementar una función que vea si existe un monstruo dentro del calabozo al que acabamos de entrar. 
Retornar un puntero al mostruo si es que hay, y un NULL si no existe. 
También podriamos crear las siguientes funciones para validar:
int es_vivo_monstruo(); y/o int es_muerto_monstruo();

**Comment by pedromind** [comment]
tambien hay algo que agregar con respecto a si el monstruo esta dormido o está despierto
