### ISSUE TITLE
Escoger estado del monstruo a partir de un random.

### ISSUE THREAD

**Issue by yieeei** [IC-ULS/edd-taller2-g1#34]
Esto iría agregado a la función *inicializa_monstruo();
0=No existe monstruo
1=Existe monstruo despierto
2=Existe monstruo dormido
3=Monstruo está muerto.

Cabe destacar que si el calabozo es una hoja, esta debe tener sí o si un monstruo dentro.

**Comment by falvarezortiz** [comment]
Solucionado.
