### ISSUE TITLE
Solucionar escoger raza (random). en monstruo//SOLUCIONADO

### ISSUE THREAD

**Issue by yieeei** [IC-ULS/edd-taller2-g1#35]
Resulta que desconozco la cantidad de monstruo que puede traer cada archivo Monstruos.csv. Entonces habría que tener una cabecera con la cantidad de razas en en el archivo csv, ó recorrer la lista enlazada monstruos. (Monstruo y Monstruos son dos estructuras distintas.Monstruos posee los tipos de monstruos tomados desde el archivo)

**Comment by falvarezortiz** [comment]
Solucionad-.
